import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Finance App",
  description: "Generated by create next app",
  manifest: "/manifest.json", 
  icons: {
    icon: "/icons/icon-192x192.png",
    apple: "/icons/icon-192x192.png", 
  },
  appleWebApp: {
    capable: true, 
    statusBarStyle: "default", 
    title: "Finance App",
  },
};

export const viewport: Viewport = {
  themeColor: "#ffffff",
};

import { Toaster } from "@/components/ui/sonner"
import { Providers } from "@/providers/providers";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        {/* Manifest y configuración de la PWA */}
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/icons/icon-192x192.png" />
        <link rel="apple-touch-icon" href="/icons/icon-192x192.png" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
      </head>
      <body className={inter.className}>
        <Providers>
            {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}